# -*- coding: utf-8 -*-
"""Per5K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBaP5vZKYdbxM7RR2eN9b6Fae9JXQmqJ
"""

import matplotlib.pyplot as plt

x = [4, 5, 10, 4, 3, 11, 14 , 6, 10, 12]
y = [21, 19, 24, 17, 16, 25, 24, 22, 21, 21]

plt.scatter(x, y)
plt.show()

from sklearn.cluster import KMeans

data = list(zip(x, y))
inertias = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i)
    kmeans.fit(data)
    inertias.append(kmeans.inertia_)

plt.plot(range(1,11), inertias, marker='o')
plt.title('Elbow method')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.show()

kmeans = KMeans(n_clusters=2)
kmeans.fit(data)

plt.scatter(x, y, c=kmeans.labels_)
plt.show()

import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Data
data = np.array([
    [89, 90, 75],   # Imam
    [90, 71, 95],   # Clarisa
    [70, 75, 80],   # Iqbal
    [45, 65, 59],   # Dilan
    [65, 75, 53],   # Ratna
    [80, 70, 75],   # Meilia
    [90, 85, 81],   # Rudi
    [70, 70, 73],   # Hafiz
    [96, 93, 85],   # Tito
    [60, 55, 48],   # Bima
    [45, 60, 58],   # Justin
    [60, 70, 72],   # Jesika
    [85, 90, 88],   # Ayu
    [52, 68, 55],   # Siska
    [40, 60, 70]    # Yusup
])

x = data[:, 0]  # UTS
y = data[:, 1]  # Tugas
z = data[:, 2]  # UAS

# KMeans clustering
kmeans = KMeans(n_clusters=3)
kmeans.fit(data)
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Visualisasi hasil clustering
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x, y, z, c=labels, cmap='viridis', s=50, alpha=0.5)
ax.scatter(centroids[:, 0], centroids[:, 1], centroids[:, 2], c='red', s=200, marker='x')

ax.set_xlabel('UTS')
ax.set_ylabel('Tugas')
ax.set_zlabel('UAS')

plt.title('K-Means Clustering')
plt.show()